name: Vue Front Build and Push

# 1. 이벤트 트리거(on)
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    
# 3. source checkout
    steps:
    - name: Source Checkout
      uses: actions/checkout@v2
# 4. setup node
    - name: Node.js 설치
      uses: actions/setup-node@v2  # Node.js 설정 액션 사용
      with:
        node-version: '20.12.1'  # 사용할 Node.js 버전 지정
# 5. docker build

# 6. docker login

# 7. docker build and push

# 파이프라인 작성이 끝나면 로컬 콘솔에서 이미지 빌드 , 실행
# docker build ~~~~
# docker run port(8080:8080) container_name