name: Vue Front Build and Push

# 1. 이벤트 트리거(on)
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Source Checkout
        uses: actions/checkout@v2
      - name: SetUp JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
# 2. Jobs - runner 

# 3. source checkout

# 4. setup node
 
# 5. docker build

# 6. docker login

# 7. docker build and push

# 파이프라인 작성이 끝나면 로컬 콘솔에서 이미지 빌드 , 실행
# docker build ~~~~
# docker run port(8080:8080) container_name